#
name: Build Sphinx

# This workflow runs when any of the following occur:
# - A push is made to a branch called `main` or `seed`
# - A tag starting with "v" is created
# - A pull request is created or updated
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
env:
  GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GITHUB_NAME: github-actions[bot]
#
jobs:
  # This pushes the image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # テンプレートが更新されたかをチェック
      - name: Git diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      # テンプレートをPush
      - name: Add generated files to the pull request
        run: |
          git config --local user.email ${{ env.GITHUB_MAIL }}
          git config --local user.name ${{ env.GITHUB_NAME }}
          git add .
          git commit -m "Add generated HTML to the pull request"
          git push origin HEAD:${{ github.head_ref }}
        if: steps.diff.outcome == 'failure'
